<?php

/**
 * 
 * Implementation of hook_menu_alter().
 * 
 * Redirects site/register to our own function
 * @param array $items
 */

function openscholar_ldap_menu_alter(&$items) {
	$items['site/register']['page callback'] = 'openscholar_ldap_auth_check';
}

/**
 * 
 * Checks if user is authenticated. If they have, 
 * pass through to create a site. If they haven't, give them a 
 * registration form.
 */
function openscholar_ldap_auth_check() {
	global $user;
	if (in_array('authenticated user', $user->roles)) {
		return scholarregister_form_process();
	}
	else {
		drupal_goto('user', array('destination' => 'site/register'));
	}
}