<?php

include_once('os_wysiwyg_fields.features.inc');

/**
 * Implementation of hook_menu
 */
function os_wysiwyg_fields_menu() {
  $menu = array();
  $menu['admin/build/oembed/embedly'] = array(
    'type' => MENU_NORMAL_ITEM,
    'title' => t('Embedly API Key'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('os_wysiwyg_fields_api_key_form'),
    'access arguments' => array('administer site configuration'),
  );

  return $menu;
}

// i have to do both registry alter and preprocess because
// oembed does their templates in a dumb way
/**
 * Implementation of hook_theme_registry_alter
 * Adds our theme path to the list of available theme paths
 * This lets theme() find our overridden theme file
 * @param $reg - The theme registry
 */
function os_wysiwyg_fields_theme_registry_alter(&$reg) {
  $reg['oembed']['theme paths'][] = drupal_get_path('module', 'os_wysiwyg_fields').'/theme';
}

/**
 * Implementation of hook_preprocess_theme
 * Replaces the template file for oembed photo with our own
 * @param $vars
 */
function os_wysiwyg_fields_preprocess_oembed(&$vars) {
  foreach ($vars['template_files'] as &$t) {
    if ($t == 'oembed-photo') {
      $t = 'os_wysiwyg_fields-oembed-photo';
    }
  }
}

/**
 * embed.ly API key form
 * Embed.ly allows usage of its services for free, but requests
 * that devs sign up for a free account
 * Without an account, embed.ly limits the use of its services.
 * This form allows site owners to give their account info so they
 * can use embed.ly unrestricted.
 */
function os_wysiwyg_fields_api_key_form() {
  $form = array();
  $form['help_text'] = array(
    '#type' => 'markup',
    '#value' => '<p>'.t('Without an embed.ly api key, you will be restricted to 50 embedded videos through their service a day, and have access to a limited set of their providers. To increase that limit, get an API key from embed.ly and enter it here.').'</p>',
  );
  $form['os_wysiwyg_fields_api_key'] = array(
    '#title' => t('API Key'),
    '#type' => 'textfield',
    '#default_value' => variable_get('os_wysiwyg_fields_api_key', ''),
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_wysiwyg_fields_add_js
 * Adds our js file to the the wysiwyg editor
 * @param $type - the type of form
 */
function os_wysiwyg_fields_wysiwyg_fields_add_js($type) {
  switch ($type) {
    case 'node_form':
      if (file_exists($js = drupal_get_path('module', 'os_wysiwyg_fields') . "/theme/os_wysiwyg_fields.js")) {
        drupal_add_js($js);
      }
  }
}

/**
 * Implementation of hook_field_formatter_info
 * Adds a filefield formatter that will display the
 * file description and a link to the tile
 */
function os_wysiwyg_fields_field_formatter_info() {
  return array(
    'os_file_description' => array(
      'label' => t('OS: File Description'),
      'field types' => array('filefield'),
      'description' => t('Display File Description as Link to File'),
    ),
  );
}

/**
 * Implementation of hook_theme
 */
function os_wysiwyg_fields_theme() {
  return array(
    'os_wysiwyg_fields_formatter_os_file_description' => array (
      'arguments' => array(
        'element' => null,
      )
    )
  );
}

/**
 * Implementation of custom formatter
 * Returns a link pointing to the file, using the description
 * as a the text of the link
 * @param $element
 */
function theme_os_wysiwyg_fields_formatter_os_file_description($element) {
  $item = $element['#item'];
  return '<a href="'.$GLOBALS['base_path'].$item['filepath'].'">'.$item['data']['description'].'</a>';
}

/**
 * Implementation of hook_insert_styles
 * Adds our new formatter to insert's list of formatters
 */
function os_wysiwyg_fields_insert_styles() {
  return array(
    'os_file_description' => array(
      'label' => t('File Description'),
      'weight' => -10,
    ),
  );
}

/**
 * Implementation of hook_insert_content
 * Insert calls this to get the content to insert into an editor
 * @param unknown_type $item
 * @param unknown_type $style
 * @param unknown_type $widget
 */
function os_wysiwyg_fields_insert_content($item, $style, $widget) {
  $item['data']['description'] = $item['data']['description'] == '' ? '__description__' : $item['data']['description'];

  $element = array(
    '#formatter' => $style['name'],
    '#item' => $item,
  );

  return theme('os_wysiwyg_fields_formatter_' . $element['#formatter'], $element);
}

/**
 * Implementation of hook_form_alter
 * Tells the Form API to run our prerender function on the inline file and image fields
 * @param unknown_type $form
 * @param unknown_type $form_state
 * @param unknown_type $form_id
 */
function os_wysiwyg_fields_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#id'] != 'node-form') return;

  // look for filefields with wysiwyg somewhere in there
  // add prerender to change weights of buttons around
  foreach (array('field_os_inline_files', 'field_os_inline_image') as $field) {
    if (!is_array($form[$field])) continue;
    foreach ($form[$field] as $delta => $data) {
      if (is_numeric($delta)) {
        $form[$field][$delta]['#pre_render'][] = 'os_wysiwyg_fields_inline_field_prerender';
      }
    }
  }
  // remove extra oembed field
  if (is_null($form['nid']['#value'])) {
    unset($form['field_os_inline_oembed'][1]);
  }
}

/**
 * Implementation of prerender
 * Sets the default description to be the filename.
 * @param unknown_type $elements
 */
function os_wysiwyg_fields_inline_field_prerender($elements) {
  if (isset($elements['insert']))
    $elements['insert']['#weight'] = 100;

  if ($elements['#field_name'] == 'field_os_inline_files' && $elements['#post']['op'] == 'Upload' && is_array($elements['#value'])) {
    $elements['#default_value']['data']['description'] = $elements['#value']['filename'];
    $elements['data']['description']['#value'] = $elements['#value']['filename'];
  }
  return $elements;
}

/**
 * Implementation of hook_oembedprovider_alter
 * Adds our custom callback to every embedly provider
 * @param unknown_type $providers
 */
function os_wysiwyg_fields_oembedprovider_alter(&$providers) {
  // add callback so we can add the API key to the query

  $providers_full = oembedcore_provider_load_all();
  foreach ($providers_full as $p) {
    if (!$p->disabled && strpos($p->name, 'oembedembedly') !== FALSE) {
      $schemes = explode("\n", $p->scheme);
      foreach ($schemes as $scheme) {
        $pattern_replacements = array();
        $host = _oembedcore_get_host($scheme);
        if (!is_array($providers[$host])) continue;
        foreach ($providers[$host] as $regex => &$pattern) {
          if ($pos = strrpos($regex, '(.+)', strlen($regex)-5)) {
            $pattern_replacements[$regex] = substr_replace($regex, '(.*)', $pos, 4);
          }
          $pattern['callback'] = 'os_wysiwyg_fields_oembed_provider_callback';
        }
        foreach ($pattern_replacements as $old => $new) {
          $providers[$host][$new] = $providers[$host][$old];
          unset($providers[$host][$old]);
        }
      }
    }
  }
}

/**
 * Provider callback to call when getting oembed
 * Adds a param to object tags provided by oembed so dropdowns aren't covered by the flash object.
 * @param unknown_type $provider
 * @param unknown_type $url
 * @param unknown_type $matches
 * @param unknown_type $attributes
 */
function os_wysiwyg_fields_oembed_provider_callback($provider, $url, $matches, $attributes) {
  if ($api_key = variable_get('os_wysiwyg_fields_api_key', '')) {
    $attributes['key'] = $api_key;
  }

  unset($provider['callback']);
  // just use the default method since we just want to mess with the output
  $embed = oembedcore_oembed_fetch($provider, $url, $matches, $attributes);

  // DOMDocument will take a string as HTML. More forgiving than XML
  // create a DOMDocument out of the html string,
  // find any object tags in it
  // add a new 'wmode' param
  // dump it back to html
  if ($embed->html) {
    $html = new DOMDocument(null, null);
    @$html->loadHTML($embed->html);
    $object = $html->getElementsByTagName('object');
    if ($object && $object = $object->item(0)) {
      //$object = $object->item(0);
      $param = $html->createElement('param', 'transparent');
      $param->setAttribute('name', 'wmode');
      $param->setAttribute('value', 'transparent');
      $object->appendChild($param);

      if ($embed_tag = $html->getElementsByTagName('embed')) {
        $embed_tag = $embed_tag->item(0);
        $embed_tag->setAttribute('wmode', 'transparent');
      }

      $embed->html = $html->saveHTML();
    }
  }

  return $embed;
}
