<?php

include_once('scholar_reader.features.inc');

function scholar_reader_init(){
  drupal_add_css(drupal_get_path('module', 'scholar_reader') .'/theme/scholar-reader.css');
}

/**
 * Implementation of hook_context_links_alter().
 */
function scholar_reader_context_links_alter(&$links) {
  if (!empty($links['feed'])) {
    $links['feed']['query'] = drupal_get_destination();
  }
}

/**
 * Implementation of hook_data_views_handlers_alter().
 */
function scholar_reader_data_views_handlers_alter(&$handlers) {
  dpm($handlers);
  $handlers['field']['scholar_reader_handler_field_description'] = 'scholar_reader_handler_field_description';
}


/**
 * Implementation of hook_form_alter().
 * Used to add validation to the feed addition
 */
function scholar_reader_form_alter(&$form, $form_state, $form_id) {
  // Content type form.
  if ($form_id == 'feed_node_form' && $form['type']['#value'] == 'feed') {
    $form['#validate'][] = 'scholar_reader_feed_validate';

    if(!$form['#vertical_tabs']) $form['#vertical_tabs'] = array();
    $form['#vertical_tabs']['feeds'] = 0; //Disable vert. tabs
    
    // add a description to feed url
    $form['feeds']['FeedsHTTPFetcher']['source']['#description'] = t('Enter a feed URL (e.g. "http://feeds.nytimes.com/nyt/rss/Science") ');
  }
}

/**
 * Validate the feed
 *
 * @param $form
 * @param $form_state
 */
function scholar_reader_feed_validate($form, &$form_state) {
  if (!strlen($form_state['values']['feeds']['FeedsHTTPFetcher']['source'])) {
    return;
  }

  $form_state['values']['feeds']['FeedsHTTPFetcher']['source'] = trim($form_state['values']['feeds']['FeedsHTTPFetcher']['source']);

  $form_state['values']['feeds']['FeedsHTTPFetcher']['source'] = str_ireplace("feed:http://","http://",$form_state['values']['feeds']['FeedsHTTPFetcher']['source']); //For Safari Users

  $form_state['values']['feeds']['FeedsHTTPFetcher']['source'] = str_ireplace("feed://","http://",$form_state['values']['feeds']['FeedsHTTPFetcher']['source']); //For Safari Users

  $success = (valid_url($form_state['values']['feeds']['FeedsHTTPFetcher']['source'],true) && ($status = drupal_http_request($form_state['values']['feeds']['FeedsHTTPFetcher']['source'])) && !strlen($status->error));
  if(!$success){
  	form_error($form, t('Can\'t connect to '.$form_state['values']['feeds']['FeedsHTTPFetcher']['source'].'. Invalid feed URL, please check that the URL is valid.'), 'error');
  }
}