<?php
/**
 * Implementation of hook_block().
 * @param string $op one of "list", "view", "save" and "configure"
 * @param integer $delta code to identify the block
 * @param array $edit only for "save" operation
*/

/**
 * Generate HTML for the onthisdate block
 * @param op the operation from the URL
 * @param delta offset
 * @returns block HTML 
 */
function userinfo_block($op='list', $delta=0) {
  // set up an empty array which will contain the block contents
  $block = array();

  if ($op == "list") {
    // Generate listing of blocks from this module, for the admin/block page
    $block[0]["info"] = t('On This Date');
  } 
  else if ($op == 'view') {
    // Generate our block content
 print"I am here";
// global $base_path;
 $current_path = drupal_get_path_alias($_GET["q"]);
echo $current_path;
echo $request_uri();
 //echo argv(1);
//echo "this is homepage". argv(0); 

//echo "this is homepage". arg(2); 
// print 'arg(1)';
// print"<pre>";
// $node_load("$node");
// print_r($node);
 
    // Get today's date
   // $today = getdate();

    // calculate midnight one week ago
    //$start_time = mktime(0, 0, 0,
      // $today['mon'], ($today['mday'] - 7), $today['year']);

    // we want items that occur only on the day in question, so   
    // calculate 1 day
    //$end_time = $start_time + 86400;  
    // 60 * 60 * 24 = 86400 seconds in a day
    

   // more coming...
  }

  // return the built content
  return $block;
}
?>